steps:
# build the springboot jar.
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    
# build the docker image with tag or commit id
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/basicspringbootanddocker:$REVISION_ID', '.']
    
# build the docker image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/basicspringbootanddocker:latest', '.']
    
# Push the image to Google Cloud Registry
  #- name: gcr.io/cloud-builders/docker
    #args:
      #- push
      #- gcr.io/$PROJECT_ID/basicspringbootanddocker

# re-apply all the kubernetes config file in k8s folder for deploying the changes.
  #- name: 'gcr.io/cloud-builders/kubectl'
    #args: ['apply', '-f', 'k8s/']
    #env:
    #- 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    #- 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'

# apply the new app image to the deployment
#- name: 'gcr.io/cloud-builders/kubectl'
   #args:
   #- set 
   #- image
   #- deployment 
   #- basicspringbootanddocker-backendapp-deployment 
   #- backend-app-container=gcr.io/$PROJECT_ID/basicspringbootanddocker:$COMMIT_SHA

# Push the image to Google Cloud Registry
images:
  - 'gcr.io/$PROJECT_ID/basicspringbootanddocker:$REVISION_ID'
  - 'gcr.io/$PROJECT_ID/basicspringbootanddocker:latest'
