steps:
# build the springboot jar  
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
    
# build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/basicspringbootanddocker', '.']
    
# Push the image to Google Cloud Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/basicspringbootanddocker

# re-apply the all the kubernetes config file for deploying the changes.
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'

# apply the new app image to the deployment
#- name: 'gcr.io/cloud-builders/kubectl'
   #args:
   #- set 
   #- image
   #- deployment 
   #- basicspringbootanddocker-backendapp-deployment 
   #- backend-app-container=gcr.io/$PROJECT_ID/basicspringbootanddocker:$COMMIT_SHA
